############################################################
# Dockerfile to build reddcoind container images
# Based on Ubuntu
############################################################

FROM ubuntu:14.04
MAINTAINER laudney

RUN apt-get update
RUN apt-get install -y git make g++ python-leveldb libboost-all-dev libssl-dev libdb++-dev pkg-config libminiupnpc-dev wget xz-utils
RUN apt-get clean

RUN adduser reddcoin --disabled-password
USER reddcoin

WORKDIR /home/reddcoin
RUN mkdir bin src
RUN echo PATH=\"\$HOME/bin:\$PATH\" >> .bash_profile

WORKDIR /home/reddcoin/src
RUN git clone https://github.com/reddcoin-project/reddcoin.git

WORKDIR	/home/reddcoin/src/reddcoin/src
RUN make -f makefile.unix
RUN strip reddcoind
RUN cp -f reddcoind /home/reddcoin/bin/
RUN make -f makefile.unix clean

WORKDIR	 /home/reddcoin
RUN mkdir .reddcoin
RUN cp -f src/reddcoin/contrib/docker/reddcoin.conf .reddcoin/

WORKDIR /home/reddcoin/.reddcoin
RUN wget -q https://github.com/reddcoin-project/reddcoin/releases/download/v1.3.1.2/bootstrap.dat.xz

ENV HOME /home/reddcoin
EXPOSE 8332
USER reddcoin
