############################################################
# Dockerfile to build reddcoind container images
# Based on Ubuntu
############################################################

FROM ubuntu
MAINTAINER laudney

RUN apt-get update
RUN apt-get install -y git make g++ python-leveldb libboost-all-dev libssl-dev libdb++-dev pkg-config libminiupnpc-dev wget xz-utils

RUN adduser reddcoin --disabled-password
RUN su - reddcoin
RUN mkdir ~/bin ~/src
RUN echo PATH=\"\$HOME/bin:\$PATH\" >> ~/.bash_profile
RUN echo $PATH

RUN cd ~/src
RUN git clone https://github.com/reddcoin-project/reddcoin.git
RUN cd reddcoin/src
RUN make -f makefile.unix
RUN strip ~/src/reddcoin/src/reddcoind
RUN cp -f ~/src/reddcoin/src/reddcoind ~/bin/reddcoind

RUN mkdir ~/.reddcoin
RUN cp ~/src/reddcoin/contrib/docker/reddcoin.conf ~/.reddcoin/

RUN cd ~/.reddcoin
RUN wget https://github.com/reddcoin-project/reddcoin/releases/download/v1.3.1.2/bootstrap.dat.xz
RUN xz -d bootstrap.dat.xz
RUN ~/bin/reddcoind

EXPOSE 8332
USER reddcoin
WORKDIR ~/
ENTRYPOINT ~/bin/reddcoind
