###############################################################
# Dockerfile to build reddcoin-electrum server container images
# Based on Ubuntu
###############################################################

FROM ubuntu:14.04
MAINTAINER laudney

RUN apt-get update
RUN apt-get install -y git make g++ python-setuptools python-openssl python-leveldb python-dev libleveldb-dev wget
RUN apt-get clean
RUN easy_install jsonrpclib irc plyvel

RUN adduser reddcoin --disabled-password
USER reddcoin

WORKDIR /home/reddcoin
RUN mkdir bin src
RUN echo PATH=\"\$HOME/bin:\$PATH\" >> .bash_profile

WORKDIR /home/reddcoin/src
RUN git clone https://github.com/reddcoin-project/reddcoin-electrum-server.git

USER root
WORKDIR /home/reddcoin/src/reddcoin-electrum-server
RUN ./configure
RUN python setup.py install

WORKDIR /var
RUN touch /var/log/electrum.log
RUN chown reddcoin:reddcoin /var/log/electrum.log
RUN wget -q http://reddwallet.org/electrum.tar.gz
RUN tar -zxvf electrum.tar.gz
RUN rm electrum.tar.gz
RUN chown reddcoin:reddcoin -R electrum-server

RUN echo "reddcoin hard nofile 65536" >> /etc/security/limits.conf
RUN echo "reddcoin soft nofile 65536" >> /etc/security/limits.conf

USER reddcoin
WORKDIR	/home/reddcoin
RUN openssl genrsa -des3 -passout pass:x -out server.pass.key 2048
RUN openssl rsa -passin pass:x -in server.pass.key -out server.key
RUN rm server.pass.key
RUN openssl req -new -key server.key -out server.csr -subj '/CN=www.my.com/O=My Company Name LTD./C=US'
RUN openssl x509 -req -days 730 -in server.csr -signkey server.key -out server.crt

ENV HOME /root
EXPOSE 50001 50002
USER root
